apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub.GolfLeague
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: publishingScopes
    value: "score-service=scores;roster-service=golfers"
  - name: subscriptionScopes
    value: "score-service=golfers;roster-service=scores"
scopes:
- roster-service
- score-service